services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    volumes:
      - ${BACKREST_DIR}/data:/data
      - ${BACKREST_DIR}/config:/config
      - ${BACKREST_DIR}/cache:/cache
      - ${BACKREST_DIR}/tmp:/tmp
      - ${BACKREST_BACKUP_DIR}:/userdata # Mount local paths to backup
      # - /path/to/local/repos:/repos     # Mount local repos (optional for remote storage)
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=Europe/Rome
    restart: unless-stopped
    ports:
      - 9898:9898
